_core:
  default_config_hash: NGxFi-xycxrzrGVZtCUl7MACi0jVRk130tNabvIN6ng
content_root: ''
no_load: '.details, body'
ignore_containers: ''
embedded_content_warning: ''
allow_overflow: ''
assertiveness: smart
download_links: ''
ignore_link_strings: ''
hidden_handlers: ''
langcode: eng
