_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: eng
uuid: c6addb00-3251-4e17-bd38-de93abc61622
name: 'Austin Public Library'
mail: drupaladmin@austintexas.gov
slogan: ''
page:
  403: /node/2
  404: /node/7724406
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
