_core:
  default_config_hash: 9DgabkLztscclWQDjei_mAOpxP6xdbp_Iu5L5z6Nsbg
langcode: eng
sids:
  coa: coa
  coa2: '0'
  coa3: '0'
  coa4: '0'
  test_server: '0'
authenticationMode: mixed
loginUIUsernameTxt: ''
loginUIPasswordTxt: ''
ldapUserHelpLinkUrl: ''
ldapUserHelpLinkText: ''
emailOption: disable
emailUpdate: update
emailTemplateHandling: none
emailTemplate: '@username@example.com'
emailTemplateUsageResolveConflict: false
emailTemplateUsageNeverUpdate: false
emailTemplateUsagePromptUser: false
emailTemplateUsageRedirectOnLogin: false
emailTemplateUsagePromptRegex: '.*@example\\.com'
passwordOption: disable
allowOnlyIfTextInDn: {  }
excludeIfTextInDn: {  }
excludeIfNoAuthorizations: false
skipAdministrators: false
