features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
uswds_header_style: extended
uswds_header_mega: 0
uswds_header_mega_display_second: 0
uswds_government_banner: 0
uswds_government_banner_mil: 0
uswds_footer_style: big
uswds_footer_agency: 0
uswds_footer_agency_name: ''
uswds_footer_agency_url: ''
uswds_footer_agency_logo: ''
uswds_contact_center: ''
uswds_email: ''
uswds_phone: ''
uswds_facebook: ''
uswds_twitter: ''
uswds_youtube: ''
uswds_rss: ''
uswds_paragraphs_edge_to_edge: 0
uswds_menu_accordion_duplicate_parent: 0
uswds_menu_bypass:
  primary_menu: primary_menu
  secondary_menu: secondary_menu
  sidebar_first: sidebar_first
  sidebar_second: sidebar_second
  footer_menu: footer_menu
uswds_search_bypass: 1
uswds_search_style: small
uswds_form_optional_label: 0
